import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Index.module.css";
import Header from "../components/header/header.component";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.header}>
        <Header />
      </div>
    </div>
  );
};

export default Home;
